-- 使用 vim-startify 的样式
require("alpha").setup(require("alpha.themes.startify").config)

-- local dashboard = require('alpha.themes.dashboard')
-- require('alpha').setup(dashboard.opts)
--dashboard.section.header.val = {
--    '',
--    '    ████▌█████▌█ ████████▐▀██▀    ',
--    '  ▄█████ █████▌ █ ▀██████▌█▄▄▀▄   ',
--    '  ▌███▌█ ▐███▌▌  ▄▄ ▌█▌███▐███ ▀  ',
--    ' ▐ ▐██  ▄▄▐▀█   ▐▄█▀▌█▐███▐█      ',
--    '   ███ ▌▄█▌  ▀  ▀██  ▀██████▌     ',
--    '    ▀█▌▀██▀ ▄         ███▐███     ',
--    '     ██▌             ▐███████▌    ',
--    '     ███     ▀█▀     ▐██▐███▀▌    ',
--    '     ▌█▌█▄         ▄▄████▀ ▀      ',
--    '       █▀██▄▄▄ ▄▄▀▀▒█▀█           ',
--    ''
--}
--
--dashboard.section.footer.val = {
--    'Highlord Mograine . The Ashbringer',
--}
--
